#!/usr/bin/env python3
"""Build the Windows one-click installer (NSIS setup.exe).

Usage:
    python3 scripts/build_installer.py [version] [exe] [outdir]

Defaults: version from argv (or 1.0.0), exe build/out/LedgerPOS.exe,
outdir build/netlify-site/downloads (same folder the landing page serves).

Produces ledgerpos-setup-windows-x64-<version>.exe: a per-user installer
(HKCU, no UAC prompt) that installs to %LOCALAPPDATA%\\Programs\\LedgerPOS,
writes Desktop + Start Menu shortcuts and the Add/Remove Programs entry,
then offers to launch. First run detects the install dir and skips the
exe's own self-install, so installer and portable flows never fight.

Requires NSIS (makensis): winget install NSIS.NSIS, apt install nsis, or
brew install nsis. Without it, the .nsi is still written next to the output
and this script prints the manual command (CI installs NSIS first).
"""

import os
import shutil
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
APP = "LedgerPOS"
VERSION = sys.argv[1] if len(sys.argv) > 1 else "1.0.0"
EXE = sys.argv[2] if len(sys.argv) > 2 else os.path.join(ROOT, "build", "out", "LedgerPOS.exe")
OUTDIR = sys.argv[3] if len(sys.argv) > 3 else os.path.join(ROOT, "build", "netlify-site", "downloads")

NSI_TEMPLATE = r""";; LedgerPOS Windows installer (generated by scripts/build_installer.py — do not edit).
Unicode true
!include "MUI2.nsh"

Name "__APP__"
OutFile "__OUTFILE__"
InstallDir "$LOCALAPPDATA\Programs\__APP__"
RequestExecutionLevel user
ShowInstDetails nevershow
ShowUninstDetails nevershow

!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!define MUI_FINISHPAGE_RUN "$INSTDIR\__APP__.exe"
!define MUI_FINISHPAGE_RUN_TEXT "Launch __APP__ now"
!insertmacro MUI_PAGE_FINISH
!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES
!insertmacro MUI_LANGUAGE "English"

Section "Install"
  SetOutPath "$INSTDIR"
  File "__EXE__"
  CreateShortCut "$DESKTOP\__APP__.lnk" "$INSTDIR\__APP__.exe" "" "$INSTDIR\__APP__.exe" 0
  CreateDirectory "$SMPROGRAMS\__APP__"
  CreateShortCut "$SMPROGRAMS\__APP__\__APP__.lnk" "$INSTDIR\__APP__.exe" "" "$INSTDIR\__APP__.exe" 0
  WriteUninstaller "$INSTDIR\uninstall.exe"
  WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\__APP__" "DisplayName" "__APP__ (Point of Sale)"
  WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\__APP__" "DisplayVersion" "__VERSION__"
  WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\__APP__" "InstallLocation" "$INSTDIR"
  WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\__APP__" "UninstallString" "$INSTDIR\uninstall.exe"
  WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\__APP__" "DisplayIcon" "$INSTDIR\__APP__.exe,0"
  WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\__APP__" "Publisher" "__APP__"
  WriteRegDWORD HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\__APP__" "NoModify" 1
  WriteRegDWORD HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\__APP__" "NoRepair" 1
SectionEnd

Section "Uninstall"
  Delete "$DESKTOP\__APP__.lnk"
  Delete "$SMPROGRAMS\__APP__\__APP__.lnk"
  RMDir "$SMPROGRAMS\__APP__"
  DeleteRegKey HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\__APP__"
  Delete "$INSTDIR\__APP__.exe"
  Delete "$INSTDIR\uninstall.exe"
  RMDir "$INSTDIR"
SectionEnd
"""


def find_makensis():
    found = shutil.which("makensis")
    if found:
        return found
    for candidate in (
        r"C:\Program Files (x86)\NSIS\makensis.exe",
        r"C:\Program Files\NSIS\makensis.exe",
    ):
        if os.path.isfile(candidate):
            return candidate
    return None


def main():
    if not os.path.isfile(EXE):
        print(f"missing exe: {EXE} (build it first: go build)")
        return 2
    os.makedirs(OUTDIR, exist_ok=True)
    outname = f"ledgerpos-setup-windows-x64-{VERSION}.exe"
    outpath = os.path.join(OUTDIR, outname)
    nsipath = os.path.join(OUTDIR, "ledgerpos-setup.nsi")
    script = (
        NSI_TEMPLATE.replace("__APP__", APP)
        .replace("__VERSION__", VERSION)
        .replace("__EXE__", os.path.abspath(EXE).replace("/", "\\"))
        .replace("__OUTFILE__", os.path.abspath(outpath).replace("/", "\\"))
    )
    with open(nsipath, "w", encoding="utf-8") as f:
        f.write(script)
    print(f"wrote {nsipath}")
    makensis = find_makensis()
    if not makensis:
        print("makensis not found — install NSIS, then run:")
        print(f'  makensis "{nsipath}"')
        print("(CI: winget install NSIS.NSIS / apt install nsis / brew install nsis)")
        return 3
    print(f"$ {makensis} {nsipath}")
    subprocess.run([makensis, nsipath], check=True)
    size_mb = os.path.getsize(outpath) / 1e6
    print(f"-> {outname}  {size_mb:.1f} MB")
    return 0


if __name__ == "__main__":
    sys.exit(main())
