#!/usr/bin/env python3
"""Build the Windows one-click installer (NSIS setup.exe).

Usage:
    python3 scripts/build_installer.py [version] [exe] [outdir]

Defaults: version from argv (or 1.0.0), exe build/out/LedgerPOS.exe,
outdir build/netlify-site/downloads (same folder the landing page serves).

Produces ledgerpos-setup-windows-x64-<version>.exe: a per-user installer
(HKCU, no UAC prompt) that installs to %LOCALAPPDATA%\\Programs\\LedgerPOS,
writes Desktop + Start Menu shortcuts and the Add/Remove Programs entry,
then offers to launch. First run detects the install dir and skips the
exe's own self-install, so installer and portable flows never fight.

Requires NSIS (makensis): winget install NSIS.NSIS, apt install nsis, or
brew install nsis. Without it, the .nsi is still written next to the output
and this script prints the manual command (CI installs NSIS first).
"""

import os
import shutil
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
APP = "LedgerPOS"
VERSION = sys.argv[1] if len(sys.argv) > 1 else "1.0.0"
EXE = sys.argv[2] if len(sys.argv) > 2 else os.path.join(ROOT, "build", "out", "LedgerPOS.exe")
OUTDIR = sys.argv[3] if len(sys.argv) > 3 else os.path.join(ROOT, "build", "netlify-site", "downloads")

NSI_TEMPLATE = r""";; LedgerPOS Windows installer (generated by scripts/build_installer.py — do not edit).
Unicode true
!include "MUI2.nsh"

; Solid LZMA: the app payload keeps growing (embedded frontend) and the
; Netlify drag-and-drop guard caps assets at 10 MB.
SetCompressor /SOLID lzma

Name "__APP__"
OutFile "__OUTFILE__"
InstallDir "$LOCALAPPDATA\Programs\__APP__"
RequestExecutionLevel user
ShowInstDetails nevershow
ShowUninstDetails nevershow

!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!define MUI_FINISHPAGE_RUN "$INSTDIR\__APP__.exe"
!define MUI_FINISHPAGE_RUN_TEXT "Launch __APP__ now"
!insertmacro MUI_PAGE_FINISH
!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES
!insertmacro MUI_LANGUAGE "English"

Section "Install"
  SetOutPath "$INSTDIR"
  File "__EXE__"
  CreateShortCut "$DESKTOP\__APP__.lnk" "$INSTDIR\__APP__.exe" "" "$INSTDIR\__APP__.exe" 0
  CreateDirectory "$SMPROGRAMS\__APP__"
  CreateShortCut "$SMPROGRAMS\__APP__\__APP__.lnk" "$INSTDIR\__APP__.exe" "" "$INSTDIR\__APP__.exe" 0
  WriteUninstaller "$INSTDIR\uninstall.exe"
  WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\__APP__" "DisplayName" "__APP__ (Point of Sale)"
  WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\__APP__" "DisplayVersion" "__VERSION__"
  WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\__APP__" "InstallLocation" "$INSTDIR"
  WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\__APP__" "UninstallString" "$INSTDIR\uninstall.exe"
  WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\__APP__" "DisplayIcon" "$INSTDIR\__APP__.exe,0"
  WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\__APP__" "Publisher" "__APP__"
  WriteRegDWORD HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\__APP__" "NoModify" 1
  WriteRegDWORD HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\__APP__" "NoRepair" 1
SectionEnd

Section "Uninstall"
  Delete "$DESKTOP\__APP__.lnk"
  Delete "$SMPROGRAMS\__APP__\__APP__.lnk"
  RMDir "$SMPROGRAMS\__APP__"
  DeleteRegKey HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\__APP__"
  Delete "$INSTDIR\__APP__.exe"
  Delete "$INSTDIR\uninstall.exe"
  RMDir "$INSTDIR"
SectionEnd
"""


def find_makensis():
    found = shutil.which("makensis")
    if found:
        return found
    for candidate in (
        r"C:\Program Files (x86)\NSIS\makensis.exe",
        r"C:\Program Files\NSIS\makensis.exe",
    ):
        if os.path.isfile(candidate):
            return candidate
    return None


GOVERSIONINFO = "github.com/josephspurrier/goversioninfo/cmd/goversioninfo@v1.7.0"


def version_parts():
    nums = (VERSION.lstrip("v") + ".0.0.0").split(".")[:4]
    return [int(n) if n.isdigit() else 0 for n in nums]


def stamp_version_info():
    """Ensure a version-stamped resource syso exists for the Windows build.

    package_desktop.py step 1 already produces rsrc_windows_amd64.syso via
    go-winres (icon + manifest + version). goversioninfo output is rejected
    by the Linux linker ("adddynlib: unsupported binary format"), so reuse
    the go-winres artifact and only fall back to goversioninfo when absent.
    """
    import json

    if os.path.isfile(os.path.join(ROOT, "rsrc_windows_amd64.syso")):
        print("-> using existing rsrc_windows_amd64.syso (go-winres stamp)")
        return 0
    major, minor, patch, build = version_parts()
    info = {
        "FixedFileInfo": {
            "FileVersion": {"Major": major, "Minor": minor, "Patch": patch, "Build": build},
            "ProductVersion": {"Major": major, "Minor": minor, "Patch": patch, "Build": build},
            "FileFlagsMask": "3f",
            "FileFlags": "00",
            "FileOS": "040004",
            "FileType": "01",
            "FileSubType": "00",
        },
        "StringFileInfo": {
            "Comments": "Point of sale for Kenyan retail shops",
            "CompanyName": "LedgerPOS",
            "FileDescription": "LedgerPOS point of sale",
            "FileVersion": VERSION.lstrip("v"),
            "InternalName": "ledgerpos",
            "LegalCopyright": "",
            "OriginalFilename": "LedgerPOS.exe",
            "ProductName": "LedgerPOS",
            "ProductVersion": VERSION.lstrip("v"),
        },
        "VarFileInfo": {"Translation": {"LangID": "0409", "CharsetID": "04B0"}},
    }
    # Icon + manifest merge into the same syso (replaces the old committed
    # rsrc_windows_amd64.syso blob — its sources now live in version control:
    # scripts/assets/app.manifest and build/app.ico from make_icon.py).
    ico_path = os.path.join(ROOT, "build", "app.ico")
    manifest_path = os.path.join(ROOT, "scripts", "assets", "app.manifest")
    # NOTE: forward slashes only — goversioninfo runs on Linux CI too, where
    # a "\\"-joined path is a literal filename and the stamp step fails.
    if os.path.isfile(ico_path):
        info["IconPath"] = ico_path
    else:
        print("no build/app.ico (run scripts/make_icon.py) — exe ships without icon")
    if os.path.isfile(manifest_path):
        info["ManifestPath"] = manifest_path
    else:
        print("no scripts/assets/app.manifest — exe ships without manifest")
    json_path = os.path.join(ROOT, "versioninfo.json")
    syso_path = os.path.join(ROOT, "resource_windows_amd64.syso")
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(info, f, indent=2)
    print(f"$ go run {GOVERSIONINFO} -o {syso_path}")
    go = (
        os.environ.get("GO_BIN")
        or shutil.which("go")
        or next(
            (p for p in (
                r"C:\Program Files\Go\bin\go.exe",
                r"C:\Go\bin\go.exe",
                os.path.expandvars(r"%LOCALAPPDATA%\go\bin\go.exe"),
            ) if os.path.isfile(p)),
            None,
        )
    )
    if not go:
        print("go toolchain not found (PATH or GO_BIN env) — cannot stamp version info")
        return 1
    subprocess.run(
        [go, "run", GOVERSIONINFO, "-o", syso_path, json_path],
        check=True,
        cwd=ROOT,
    )
    print(f"-> versioninfo {VERSION} stamped into {syso_path}")
    return 0


def find_go():
    return (
        os.environ.get("GO_BIN")
        or shutil.which("go")
        or next(
            (p for p in (
                r"C:\Program Files\Go\bin\go.exe",
                r"C:\Program Files (x86)\Go\bin\go.exe",
                r"C:\Go\bin\go.exe",
                os.path.expandvars(r"%LOCALAPPDATA%\go\bin\go.exe"),
            ) if os.path.isfile(p)),
            None,
        )
    )


def build_exe():
    """Build the version-stamped Windows exe (picks up resource_*.syso)."""
    go = find_go()
    if not go:
        print("go toolchain not found (PATH or GO_BIN env)")
        return 1
    os.makedirs(os.path.dirname(os.path.abspath(EXE)), exist_ok=True)
    env = dict(os.environ, GOOS="windows", GOARCH="amd64", CGO_ENABLED="0")
    cmd = [
        go, "build", "-trimpath",
        "-ldflags", f"-s -w -X main.version={VERSION} -H=windowsgui",
        "-o", os.path.abspath(EXE), ".",
    ]
    print("$ " + " ".join(cmd))
    subprocess.run(cmd, check=True, cwd=ROOT, env=env)
    return 0


def main():
    if stamp_version_info() != 0:
        return 2
    if build_exe() != 0:
        return 2
    if not os.path.isfile(EXE):
        print(f"missing exe after build: {EXE}")
        return 2
    os.makedirs(OUTDIR, exist_ok=True)
    outname = f"ledgerpos-setup-windows-x64-{VERSION}.exe"
    outpath = os.path.join(OUTDIR, outname)
    nsipath = os.path.join(OUTDIR, "ledgerpos-setup.nsi")
    script = (
        NSI_TEMPLATE.replace("__APP__", APP)
        .replace("__VERSION__", VERSION)
        .replace("__EXE__", os.path.abspath(EXE).replace("/", "\\"))
        .replace("__OUTFILE__", os.path.abspath(outpath).replace("/", "\\"))
    )
    with open(nsipath, "w", encoding="utf-8") as f:
        f.write(script)
    print(f"wrote {nsipath}")
    makensis = find_makensis()
    if not makensis:
        print("makensis not found — install NSIS, then run:")
        print(f'  makensis "{nsipath}"')
        print("(CI: winget install NSIS.NSIS / apt install nsis / brew install nsis)")
        return 3
    print(f"$ {makensis} {nsipath}")
    subprocess.run([makensis, nsipath], check=True)
    size_mb = os.path.getsize(outpath) / 1e6
    print(f"-> {outname}  {size_mb:.1f} MB")
    return 0


if __name__ == "__main__":
    sys.exit(main())
